/* autogenerated by Processing revision 1283 on 2023-02-09 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.*;
import java.io.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Flappy_Bird extends PApplet {



PImage FlappyBird;
boolean paused = true;
int xBird = 0;
int yBird = 500;
int vBird  = 0;
int score = 0;
Table HighScores;
boolean hsScreen = false;
ArrayList<Pipes> pipes;
int PipeDistance = 450;
int MAXSCORES= 5;
String textString = "";
boolean textInput = false;

 public void setup() {
  FlappyBird = loadImage("Flappy bird.png");
  /* size commented out by preprocessor */;
  pipes = new ArrayList<Pipes>();
  pipes.add(new Pipes(width, PApplet.parseInt (random(200, 800))));
  HighScores = loadTable("FlappyHighScore.csv", "header");
}

 public void draw() {
  background(0xFF9DC7FF);
  textAlign(CENTER, CENTER);
  textSize(100);
  text(score, 500, 100);
  image(FlappyBird, xBird, yBird, 150, 120);
  if (paused == false) {
    if (yBird-vBird <= height)
      yBird -= vBird;
    if (vBird > -12)
      vBird -= 1;
    ListIterator<Pipes> itr = pipes.listIterator();
    while (itr.hasNext()) {
      Pipes pipe = itr.next();
      pipe.draw();
      if (pipe.x <= width-PipeDistance && pipe.last == true) {
        itr.add(new Pipes (PApplet.parseInt (width), PApplet.parseInt (random(200, 800))));
        pipe.last = false;
      }
      if (pipe.x <= 0) {
        itr.remove();
        score ++;
        print(score);
      } else if (pipe.checkcollision(xBird, yBird, 150, 120)) {
        paused = true;
        yBird = 500;
        break;
      }
    }

    if (paused == true) {
      pipes.clear();
      pipes.add(new Pipes(width, PApplet.parseInt (random(200, 800))));
      textInput = true;
    }
  }
  if (hsScreen == true) {
    fill(0);
    textSize(100);
    textAlign(CENTER, CENTER);
    for (int i= HighScores.getRowCount()-1; i >= max(HighScores.getRowCount() - MAXSCORES,0); i--) {
      TableRow row = HighScores.getRow(HighScores.getRowCount() -1 -i);
      text(row.getInt("score") + "   "+ row.getString("name"), width/2, 300 +i*100);
    }
  }
  if (textInput ==true) {
    fill(0);
    textSize(100);
    textAlign(CENTER, CENTER);
    text("Enter Initials", 500, 300);
    text(textString, 500, 500);
    textInput = true;
  }
}
 public void mouseClicked() {
  if(textInput == false && hsScreen == false){
  paused = false;

  vBird = 20;
  }
}
 public void keyPressed() {
  if (textInput == true) {
    if (key !=CODED) {
      String aloud ="abcdefghijklmnopqrstuvwxyz";
      String keyString = "" + key;
      if (aloud.contains(keyString.toLowerCase()))
        textString += keyString;
      else if (key == BACKSPACE && textString.length() > 0)

        textString = textString.substring(0, textString.length()-1);

      else if ( (key == ENTER || key == RETURN) &&  textString.length() > 0) {
        textInput =false;
        TableRow row = HighScores.addRow();
        row.setString("name", textString);
        row.setInt("score", score);
        HighScores.sort("score");
        saveTable(HighScores, "data/FlappyHighScore.csv");
        textString = "";
        hsScreen =true;
      }
    }
  } else if (  hsScreen == true) {
    hsScreen =false;
    score =0;
    paused = false;
  }
}
class HS implements Comparable<HS>{
String name;
Integer Score;
  public HS(String n , int Score){
name = n;
this.Score = Score;
}
 public int compareTo(HS other){
   return Score.compareTo(other.Score);
   
   
 }
  
  
  
  
  
  
  
  
  
  
}
public class Pipes {
  private int y;
  private int gapwidth = 400;
  private int x = width;
  public boolean last =true;
  private PImage Sprite = loadImage("Flappy Pipe.png");
  public Pipes(int x, int y) {

    this.x =x;
    this.y =y;
    this.last = true;
  }
  public void draw() {

    x -= 5;
    image(Sprite, x, y+gapwidth/2, 200, 750);
    pushMatrix();
    translate (x, y-gapwidth/2);
    scale(1.0f, -1.0f);


    image(Sprite, 0, 0, 200, 750);
    popMatrix();
  }
  public boolean checkcollision(int birdx, int birdy, int w, int h) {
    int r = w/2;
    int centerx = birdx + w/2;
    int centery = birdy +h/2;
    int pipe1y = this.y-(750 + gapwidth/2);
    if (birdy <= pipe1y+750 && birdy + h >= pipe1y && abs(centerx-(this.x+100))<= r) {

      return true;
    }
    int pipe2y = this.y+gapwidth/2;
    if (birdy <= pipe2y+750 && birdy + h >= pipe2y && abs(centerx-(this.x+100))<= r) {

      return true;
    }
    return false;
  }
}


  public void settings() { size(1000, 1000); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Flappy_Bird" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
